-- Enable Realtime
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime FOR ALL TABLES;

-- ROOMS TABLE
CREATE TABLE rooms (
  id TEXT PRIMARY KEY,
  name TEXT,
  host_id TEXT,
  current_video_id TEXT,
  is_playing BOOLEAN DEFAULT false,
  playback_rate NUMERIC DEFAULT 1,
  last_synced_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- MESSAGES TABLE
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT REFERENCES rooms(id) ON DELETE CASCADE,
  user_name TEXT NOT NULL,
  content TEXT NOT NULL,
  color TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- QUEUE TABLE
CREATE TABLE queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT REFERENCES rooms(id) ON DELETE CASCADE,
  video_id TEXT NOT NULL,
  title TEXT NOT NULL,
  thumbnail TEXT,
  added_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS POLICIES (Allow public access for demo purposes)
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE queue ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public rooms access" ON rooms FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public messages access" ON messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public queue access" ON queue FOR ALL USING (true) WITH CHECK (true);
